server:
  port:
    8080
  servlet:
    context-path: /


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/litemall?serverTimezone=GMT&useSSL=false
    username: root
    password: xjtuse
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10
    jedis:
      pool:
        max-active: 1000
        max-wait: 500
        max-idle: 500

logging:
  level:
    com: DEBUG